name: CI (master)

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**" # Ignore all tags to avoid duplicate executions triggered by tag pushes.

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  code_checks:
    name: Code checks
    uses: ./.github/workflows/_check_code.yaml

  tests:
    # Skip this for "ci" and "docs" commits.
    if: "!startsWith(github.event.head_commit.message, 'ci') && !startsWith(github.event.head_commit.message, 'docs')"
    name: Tests
    uses: ./.github/workflows/_tests.yaml

  beta_release:
    # Skip this for "ci", "docs" and "test" commits and for forks.
    if: "!startsWith(github.event.head_commit.message, 'ci') && !startsWith(github.event.head_commit.message, 'docs') && !startsWith(github.event.head_commit.message, 'test') && startsWith(github.repository, 'apify/')"
    name: Beta release
    needs: [code_checks, tests]
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/manual_release_beta.yaml
    secrets: inherit
