name: Run code checks

on:
  # Trigger code checks on opening a new pull request.
  pull_request:
  workflow_call:

jobs:
  lint_check:
    name: Lint check
    uses: apify/workflows/.github/workflows/python_lint_check.yaml@main
    with:
      python-versions: '["3.10", "3.11", "3.12", "3.13"]'

  type_check:
    name: Type check
    uses: apify/workflows/.github/workflows/python_type_check.yaml@main
    with:
      python-versions: '["3.10", "3.11", "3.12", "3.13"]'

  unit_tests:
    name: Unit tests
    uses: apify/workflows/.github/workflows/python_unit_tests.yaml@main
    with:
      python-versions: '["3.10", "3.11", "3.12", "3.13"]'
